services:
  app:
    image: otboo:local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otboo
    ports:
      - "8081:80"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION}
      - REFRESH_TOKEN_EXPIRATION=${REFRESH_TOKEN_EXPIRATION}
      - ISSUER=${ISSUER}


  db:
    image: postgres:15
    container_name: obtoo-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      # PostgreSQL 데이터 유지
      - db-data:/var/lib/postgresql/data
      # schema.sql 자동 실행 (컨테이너 시작 시)
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

volumes:
  db-data:
    driver: local
  storage_data:
    driver: local