server:
  port: 80

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS}
    username: ${SPRING_ELASTICSEARCH_USERNAME}
    password: ${SPRING_ELASTICSEARCH_PASSWORD}

logging:
  level:
    com.codeit.otboo: info
    org.hibernate.SQL: warn

management:
  endpoint:
    health:
      show-details: never

otboo:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}
    issuer: ${ISSUER}