spring:
  application:
    name: otboo

  profiles:
    active: dev

  sql:
    init:
      mode: never

  jpa:
    database: postgresql
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

info:
  app:
    name: OtBoo
    version: 1.0.0

sse:
  event-queue-capacity: 100
  timeout: 300_000
api:
  kma-api-key: ${KMA_API_KEY}