spring:
  application:
    name: otboo

  profiles:
    active: dev

  sql:
    init:
      mode: never

  jpa:
    database: postgresql
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  mail:
    host: smtp.naver.com
    port: 587
    username: ${NAVER_MAIL_ID}
    password: ${NAVER_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true



  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false # 앱 시작 시 배치 자동 실행 방지

otboo:
  storage:
    type: s3
    s3:
      path: binary

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

info:
  app:
    name: OtBoo
    version: 1.0.0

sse:
  event-queue-capacity: 100
  timeout: 300_000
  
api:
  kma-api-key: ${KMA_API_KEY}
  kakao-rest-api-key: ${KAKAO_REST_API_KEY}

servlet:
  multipart:
    maxFileSize: 10MB
