server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/otboo
    username: otboo
    password: otboo123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}

logging:
  level:
    org.springframework.retry: debug
    org.springframework.web.socket: debug
    org.springframework.web.messaging: debug
    org.springframework.security: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.basic: trace
    com.codeit.otboo: debug

management:
  endpoint:
    health:
      show-details: always

otboo:
  storage:
    type: s3 # local
    local:
      root-path: ./storage