server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/otboo
    username: otboo
    password: otboo123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

  elasticsearch:
    uris: http://localhost:9200

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    listener:
      ack-mode: record

logging:
  level:
    root: info

    # 애플리케이션
    com.codeit.otboo: debug

    # SQL 확인용 (필수)
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: off

    # Kafka
    org.apache.kafka: warn
    org.springframework.kafka: warn

    # Security (평소 off)
    org.springframework.security: warn

    # WebSocket / Messaging (평소 off)
    org.springframework.web.socket: warn
    org.springframework.web.messaging: warn

    # Retry
    org.springframework.retry: info

management:
  endpoint:
    health:
      show-details: always

otboo:
  jwt:
    secret: mySecretKeyForJwtTokenGeneration1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
    access-token-expiration: 900000
    refresh-token-expiration: 1209600000
    issuer: codeit
  account:
    email: admin@codeit.com
    name: admin
    password: admin